version: "3.8"
services:
  webapp:
    command: sh -c "/app/entrypoint.sh"
    build: .
    depends_on:
      - "postgres"
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/habits_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      #DATABASE_PORT: 5434
    ports:
      - "4000:4000"
  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: habits_db
    volumes:
      - "postgres:/var/lib/postgresql/data"
volumes:
  postgres: {} 